#!/bin/bash

######### SYNC ##########################################

<PATH-TO-SCRIPT>/backup-rsync       <SERVERNAME e.g: webserver.example.com>       /var/lib/postgresql     >  /<LOGFOLDER>/<SERVERNAME>.LOG
<PATH-TO-SCRIPT>/backup-rsync       <SERVERNAME e.g: webserver.example.com>       /opt    >>  /<LOGFOLDER>/<SERVERNAME>.LOG
<PATH-TO-SCRIPT>/backup-rsync       <SERVERNAME e.g: webserver.example.com>       /var    >>  /<LOGFOLDER>/<SERVERNAME>.LOG
<PATH-TO-SCRIPT>/backup-rsync       <SERVERNAME e.g: webserver.example.com>       /etc    >>  /<LOGFOLDER>/<SERVERNAME>.LOG

######### ROTATE ##########################################

<PATH-TO-SCRIPT>/backup-rotate       localhost       >> /<LOGFOLDER>/<SERVERNAME>.LOG
<PATH-TO-SCRIPT>/backup-rotate       <SERVERNAME e.g: webserver.example.com>       >>/<LOGFOLDER>/<SERVERNAME>.LOG
